### ISSUE TITLE
Server nicht threadsicher

### ISSUE THREAD

**Issue by thomsmits** [int-lecture/repo-02#3]
Die Methoden des JAX-RS-Services werden potentiell von mehreren Threads parallel aufgerufen. Deshalb sollte der Zugriff auf `messageList`  und `seqCounter` entsprechend geschützt sein.

**Comment by GurkenKater** [comment]
seqCounter und messageList sollten nun safe sein. 
11 Uhr. Deutschland. Thread-Sturm. Der seqCounter sitzt.
