### ISSUE TITLE
Chat-Server-Projekt compiliert nicht

### ISSUE THREAD

**Issue by thomsmits** [int-lecture/repo-02#5]
Nach dem Clonen des Chat-Server-Projektes und Importieren in Eclipse kommt ein Compiler-Fehler:

```
Message cannot be resolved to a type
	StorageProviderMongoDB.java	/chat-server-02/src/var	line 66
```

Es fehlt also eine Klasse `Message`.

**Comment by poesterlin** [comment]
Anbindung an StorageProviderMongoDB fertig gestellt.
